DROP TABLE IF EXISTS calendars;
CREATE TABLE IF NOT EXISTS calendars (id TEXT PRIMARY KEY, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, deleted_at DATETIME);
DROP TABLE IF EXISTS calendar_sync_tokens;
CREATE TABLE IF NOT EXISTS calendar_sync_tokens (id INTEGER PRIMARY KEY, calendar_id TEXT NOT NULL UNIQUE, token TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
DROP TABLE IF EXISTS notification_channels;
CREATE TABLE IF NOT EXISTS notification_channels (id TEXT PRIMARY KEY, calendar_id TEXT NOT NULL, resourceId TEXT NOT NULL, expiration INT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, deleted_at DATETIME);
